### ISSUE TITLE
I can't find a way to contact you :)

### ISSUE THREAD

**Issue by ywmaa** [Commodoreprime/dot.files#1]
so I am interested about your work here (upgrading to Godot 4.1)
https://github.com/Commodoreprime/gdwlroots
also what do you think about integerating this with this pull request : 
https://github.com/godotengine/godot/pull/57025

finally I am totally new to the window manager prorgamming world, so 
1- how can I help ?
2- how can I learn ?

**Comment by Commodoreprime** [comment]
Why thank you for the acknowledgment! I apologize, I’m a bit of a recluse when it comes to getting contacted, I prefer Discord, love to talk to ya more on there! I have messaged you on Discord through your server as well. Email can also work just fine if you so wish.

I’m new to window manager development as well (C++ and Godot mostly as well too). I’m treating the gdwlroots project to learn primarily, but also to update the [wlroots](https://gitlab.freedesktop.org/wlroots/wlroots) implementation into Godot as I think it is a pretty neat idea. Currently

I’m working on it on and off, another set of eyes would be greatly appreciated!

The pull request draft you linked is very interesting and something I was not aware of, very nice! The purpose, as stated before, of *this* project is to implement wlroots as faithfully as possible, in the most Godot-y way possible. The end goal being that one can write a compositor in Godot, with wlroots library binds. The pull request seems to implement the Wayland protocol as a `DisplayServer` which to my understanding only means that it would allow Godot to communicate with a Wayland compositor as a client. Still very cool and happy to see that Wayland is getting attention in the Godot community as of recent.

The pull request could at least act as a reference on how to implement various Wayland protocol elements into Godot through code, which I think would be very helpful in implementation of the bindings. Maybe I could pull some code? Unsure exactly.

To answer your questions...
1. Currently work is being done on the `4.0` branch, that branch should at least be build-able and executable but the engine crashes after adding a `WaylandOutput` node for example. There are more issues (especially with XWayland) but that was the first one that came to mind as an example.
	
	My current hurdle is trying to figure out how to write the `impl`s (i.e. `wlr_renderer_impl`). This seems to mostly stem from the fact that I don't know C++ very well, the Godot C++ code base even less and wlroots somewhat less but also more so which could be a problem lol.
	
	An `impl` in this context is basically a way for wlroots to execute custom functions that are called by the library when needed, for example, [`wlr_renderer_impl`](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/0.16/include/wlr/render/interface.h?ref_type=heads#L22) is an implementation that can be filled out by various render backends, [the render implementation with gles2](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/0.16/render/gles2/renderer.c?ref_type=heads#L531) to demonstrate. My issue is trying to fill in all of the function calls that are able to be handled and processed by Godot correctly.
	
	I suppose I could ask for help by asking how modern Godot handles rendering, not sure how familiar you are with the Godot engine source code. Logic dictates that I would ask for help in both Wayland community discussion forms as well as Godot variants but I have simply not done that, yet.
	
	Another way would be someone to bounce problems off of in order to help solve issues. I've been thinking about biting the bullet and just implementing the Wayland protocol itself and present compositor / window manager capabilities into Godot without a library getting in the way (technically speaking from what I can naively tell, Godot is almost entirely capable of being a window manager, just lacks the protocols to conduct as well as rendering directly to the Kernel frame buffer / DRM but that's a separate issue :) ).

2. They way I learned was mostly by studying the [wlroots source tree](https://gitlab.freedesktop.org/wlroots/wlroots), notably the `backend/`, `render/` and `include/wlr/` directories as well as reading parts of the [Wayland Protocol book](https://wayland-book.com/introduction.html), I mostly got terminology from that, its not entirely useful unless you want to implement the protocol *itself* into Godot. I looked at [tinywl](https://gitlab.freedesktop.org/wlroots/wlroots/-/tree/0.16/tinywl) somewhat closely to see how a compositor is barely supposed to be implemented as well. I read parts of the book beforehand then looked at wlroots as I work on gdwlroots.
	
	I am by no means an expert but from what I can tell, to learn about Wayland itself I would recommend the aforementioned wlroots source tree, read the headers, some have comments attached, the Wayland Protocol book, tinywl and also look at the [compositors section](https://github.com/natpen/awesome-wayland#compositors) of the *awesome Wayland* list to see how various compositors implement using Wayland, wlroots or some other Wayland library and lastly, there's a nifty website called [Wayland Explorer](https://wayland.app/protocols/) which explores the XML protocol definition files that are scattered across various repositories in one central place with a nice documentation interface. Unfortunately, seemingly, wlroots itself does not have any proper documentation other than the source code which makes it a bit more difficult to figure out how to jump start using the library. A lot of people say to look at [Weston](https://gitlab.freedesktop.org/wayland/weston) and [Sway](https://swaywm.org/) to see how things are done as well, I haven't personally looked at them but they might be useful.
	
	The [wayland.freedesktop.org](https://wayland.freedesktop.org/) website provides links to the protocols documentation, explanation of architecture, FAQ, as well as some contact (albeit for developer) sources, among others.
	
	If you learn anything and / or gain some insights I'd love to know as well!

Hopefully that wordy explanation helps! If you have any more questions or clarifications feel free to ask me and I'll at least try to answer!

**Comment by deralmas** [comment]
@Commodoreprime PR author here. If there's any help needed with "translating" Wayland concepts to Godot I can give an hand. I doubt that most of the code will be useful but the broad logic itself should be a fine reference.

Tell me if you need help so that I can give you my contact information :)

**Comment by Commodoreprime** [comment]
Thank you @Riteo, I'd much appreciate that! Yea I was thinking the same thing.

Like you said, the trouble I'm running into the most is that translation from C header definition to Godot handling code so I'd like to get in contact with you, Discord perhaps?

Also, do you know of any other information sources that would be helpful with this? I forgot to mention the Godot docs in my original reply but do you have / know of any other tutorials, docs, recipe books, etc... that would be helpful?

Edit: implementation -> definition

**Comment by deralmas** [comment]
@Commodoreprime

> Like you said, the trouble I'm running into the most is that translation from C header definition to Godot handling code so I'd like to get in contact with you, Discord perhaps?

I don't use discord a lot but you can find me as `@riteosiuga`. We'll have to decide a good time for making a call. I guess we can discuss it through DMs.

> Also, do you know of any other information sources that would be helpful with this? I forgot to mention the Godot docs in my original reply but do you have / know of any other tutorials, docs, recipe books, etc... that would be helpful?

Regarding Godot? There are a few old videos where reduz explained the core architecture which _sort of_ still apply, but I guess that the best documentation for this sort of core stuff will always be the code. It's very readable (feels almost like GDScript) and has quite a bit of interesting comments. I can help going through it if you need it. We can discuss this further over on discord.

Cya there!
